# Generated by Django 6.0.3 on 2026-04-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_tarea_activo_alter_tarea_completada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='card_image/'),
        ),
    ]
